enum Color {
    PRIMARY = 'PRIMARY',
    SECONDARY = 'SECONDARY',
    THIRD = 'THIRD',
    FOURTH = 'FOURTH',
    PRIMARY_TEXT_COLOR = 'PRIMARY_TEXT_COLOR',
    SECONDARY_TEXT_COLOR = 'SECONDARY_TEXT_COLOR',
    THIRD_TEXT_COLOR = 'THIRD_TEXT_COLOR',
    DANGER = 'DANGER',
    SECONDARY_DANGER = 'SECONDARY_DANGER',
    IN_PROGRESS = 'IN_PROGRESS',
    DISABLED = 'DISABLED',
    SUCCESS = 'SUCCESS',
}

export {Color};
