enum BorderRadius {
    EXTRA_SMALL = 'EXTRA_SMALL',
    SMALL = 'SMALL',
    MEDIUM = 'MEDIUM',
    LARGE = 'LARGE',
    EXTRA_LARGE = 'EXTRA_LARGE',
}

enum Size {
    BASE_WIDTH = 'BASE_WIDTH',
    BASE_HEIGHT = 'BASE_HEIGHT',
    FIT_CONTENT = 'FIT_CONTENT',

    TINY = 'TINY',
    EXTRA_SMALL = 'EXTRA_SMALL',
    SMALL = 'SMALL',
    MEDIUM = 'MEDIUM',
    BIG = 'BIG',
    LARGE = 'LARGE',
    EXTRA_LARGE = 'EXTRA_LARGE',
    EXTRA_EXTRA_LARGE = 'EXTRA_EXTRA_LARGE',
    GIANT = 'GIANT',
    EXTRA_GIANT = 'EXTRA_GIANT',
    EXTRA_EXTRA_GIANT = 'EXTRA_EXTRA_GIANT',

    SMALL_BUTTON_PADDING = 'SMALL_BUTTON_PADDING',
    LARGE_BUTTON_PADDING = 'LARGE_BUTTON_PADDING',

    SWITCHER_WIDTH = 'SWITCHER_WIDTH',

    TABS_BUTTON_SHIFT = 'TABS_BUTTON_SHIFT',

    TABS_ACTIVE_Z_INDEX = 'TABS_ACTIVE_Z_INDEX',
    TABS_BASE_Z_INDEX = 'TABS_BASE_Z_INDEX',

    SMALL_IMAGE_WIDTH = 'SMALL_IMAGE_WIDTH',
    SMALL_IMAGE_HEIGHT = 'SMALL_IMAGE_HEIGHT',
}

export {Size, BorderRadius};
